version: 3.1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
before_build:
- cmd: dotnet restore src\SimpleInjector.sln
- cmd: copy src\fake.snk src\SimpleInjector.snk
build:
  verbosity: minimal
  parallel: true
  project: src\SimpleInjector.sln
after_test:
- choco install opencover.portable
- choco install codecov
- cd src
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --framework net471 --verbosity q"
- codecov -f "results.xml" 
artifacts:
- path: '**\*.nupkg'
